### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by Discover999** [shenxiancaiCCC/Vue-Springboot-#2]
![image](https://user-images.githubusercontent.com/32007383/172362539-972dd3e4-c770-4884-a6d2-d303ea7c185a.png)

idea运行后打开9090登录无响应

**Comment by shenxiancaiCCC** [comment]
你是不是项目中的数据库地址没改，要改为你本地的数据库地址，用户名和密码都得改

**Comment by Discover999** [comment]
> 你是不是项目中的数据库地址没改，要改为你本地的数据库地址，用户名和密码都得改

![image](https://user-images.githubusercontent.com/32007383/172372207-621c57db-a7dc-468c-a79b-13c6bbb5a8f5.png)
改了的，如果数据库不对应该有log出来

**Comment by shenxiancaiCCC** [comment]
有没有一种比较蠢的可能，你只跑了前端，没跑后端

**Comment by Discover999** [comment]
> 有没有一种比较蠢的可能，你只跑了前端，没跑后端

![image](https://user-images.githubusercontent.com/32007383/172535697-c6cde6a7-23eb-4df9-8091-ea4848558e25.png)
不会吧。。。这不直接运行吗

**Comment by shenxiancaiCCC** [comment]
那你看下后端里的usercontroller，有没有user/login这个路径，我上传的源码是没有问题的。有可能是你自己改了后端代码，如果这也不能解决，我也爱莫能助了

**Comment by Keeee03** [comment]
想问一下最后解决了吗
