### ISSUE TITLE
部署和运行的问题

### ISSUE THREAD

**Issue by Noviceprogrammer** [shenxiancaiCCC/Vue-Springboot-#3]
你好，我是一个初学者，您能不能出个教程，完整的教学一下从部署到运行都怎么操作吗？

**Comment by Noviceprogrammer** [comment]
您好，部署完成后，在登录界面，点击登录为什么会出现404这种情况呢？

**Comment by 877338** [comment]
'src\utils\request.js' 中的 baseURL 改成‘./’ 开发的时候是/api 经过了代理，打包后没、/api的路径， @shenxiancaiCCC 打包后自己没有运行

**Comment by lhmwen** [comment]
为什么我的vue运行不起来
